### ISSUE TITLE
[Proposal] Add `stack` parameter to `Sequence` space

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/Gymnasium#217]
### Proposal

The `Sequence` space requires that the samples always be a tuple of the sub-spaces. 
However, if for example a `Box` is the sub-space then it is a bit weird to have example sample `= (np.array([0, 1, 2]), np.array([3, 4, 5]))` as it could be more easily stacked to `np.array([[0, 1, 2], [3, 4, 5]])`

### Pitch

I would propose that we add a parameter to `Sequence` called `stack: bool = False` to be backward compatible where if `True` then the resulting samples would be stacked. It might be possible to achieve this already with the vector `concatenate` function. 

This would require that class type return needs modifying along with the `sample` and `contains` functions. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by aaronwalsman** [comment]
Would this be done recursively if your Sequence subspace is a Tuple or Dict?  I guess the semantics could be similar to whatever the VectorEnv does with the stuff it returns (speaking of which, it would be nice to have a way to turn this off if you don't want it to stack everything for you).

If you add this, it would be good to do some type checking to make sure the subspace is something with a fixed size (doing this on Sequences of Sequences should fail, because each sub-sequence could have a different size, right?).

If this checking is done, it would probably also be a good idea for each space to be augmented with some way of telling if they are fixed-size or not (maybe this exists already?  I didn't see it just now when I looked).  Like a Box would have a property `fixed_shape` which indicates that each observation will always have the same size, or make a subclass FixedShapeSpace which inherits from Space and does nothing, but then all the Spaces with a fixed shape inherit from that so that you can do isinstance(my_space, FixedShapeSpace).  To me, any of these would be better than having some line like `if isinstance(subspace, (Box, Discrete, MultiDiscrete, ...)` directly in the Sequence code, because then any new Space additions have to modify that list both here, and you just know that at some point you'll end up with similar checks somewhere else one day.

Also if you make it recursive, you should also do recursive type checking, which starts to get a little cumbersome, but is probably fine since you're only doing this once when the env is initialized.

**Comment by aaronwalsman** [comment]
Oh yeah, I missed the is_np_flattenable property, that's great thanks!  It's nice that Dict and Tuple defer to their children to determine is_np_flattenable, so I guess that is already doing all the recursion you need anyway.
