### ISSUE TITLE
[Bug Report] `mujoco.InvertedDoublePendulum` last 2 observations (constraints) are const 0

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#228]
### Describe the bug

The last 2 observations of `InvertedDoublePendulum` are always 0
the y and z axis have no constrain forces

@rodrigodelazcano can you confirm

### Code example

```shell
import gymnasium
import numpy as np

env = gymnasium.make("InvertedDoublePendulum-v4")

for eps in range(100):
    env.reset()
    for _ in range(1000):
        obs, _, _, _ , _ = env.step(env.action_space.sample())
        assert obs[-1] == 0 and obs[-2] == 0
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
@rodrigodelazcano

**Comment by rodrigodelazcano** [comment]
@Kallinteris-Andreas you are right. I suggest labeling this issues as `enhancement` instead of `bug` since they shouldn't be adding any anomalies in the observation, only redundancy. If I'm not wrong the constant values in the observation don't affect the sample distribution.

@pseudo-rnd-thoughts this is happening because the double pendulum has three degrees of freedom. The actuated joint (base of the pendulum) slides through a rail with limits on both sides. When the base reaches one of the side limits and keeps actuating in that direction an external force in the opposite direction appears.

The other two joints are hinge joints that connect the links of the pendulum. These joints don't have any friction thus the moment arm should be 0 .

If you try this you can see how `obs[-3]` blows up when reaching each rail extreme:

```
import gymnasium
import numpy as np

env = gymnasium.make("InvertedDoublePendulum-v4", render_mode='human')
action = np.array([-1])
for eps in range(100):
    env.reset()
    action*=-1
    for _ in range(100):
        obs, _, _, _ , _ = env.step(action)
        print(obs[-3:])
```
