### ISSUE TITLE
[Bug Report] Experimental NormalizeRewardV0 may be broken

### ISSUE THREAD

**Issue by raphajaner** [Farama-Foundation/Gymnasium#271]
### Describe the bug

Hi All, 

the `NormalizeRewardV0` in `gymnasium.experimental.wrappers` may be broken. When the statistics of `RunningMeanStd(shape=())` are getting updated, the following error occurs: _numpy.AxisError: axis 0 is out of bounds for array of dimension 0._

Since the reward is a scalar, line 17 in `gymnasium.experimental.wrappers.util.RunningMeanStd` cannot be calculated due to the fixed axis in: `batch_mean = np.mean(x, axis=0)`. I noticed this issue while creating the tests for #268. **Note**: There are no tests for the experimental NormalizeRewardV0 defined.

### Code example

```shell
from gymnasium.experimental.wrappers import NormalizeRewardV0
from tests.testing_env import GenericTestEnv

def test_normalize_reward_wrapper():
    """Tests that the NormalizeReward does not throw an error."""
    # TODO: Functional correctness should be tested
    env = GenericTestEnv()
    wrapped_env = NormalizeRewardV0(env)
    wrapped_env.reset()
    wrapped_env.step(None)

test_normalize_reward_wrapper()
```

### System info

`gymnasium==0.27.0`
`numpy==1.24.1`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for raising this issue. I'm both surprised and unsurprised by this
The experimental version of the normalize wrapper is basically a copy of the previous normalize wrapper 
https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/wrappers/normalize.py

Which has associated testing unlike the experimental version - https://github.com/Farama-Foundation/Gymnasium/blob/main/tests/wrappers/test_normalize.py

However, an issue was noted in gym that I suspect has always existed for the wrapper since its existence therefore, finding another bug wouldn't be surprising. It is fixed in gymnasium.
https://github.com/openai/gym/pull/3152

Could you see if there is an issue with the old testing that missed this or there is an issue with your test.

**Comment by raphajaner** [comment]
I think I found the cause of this :) The old version was using 
```python
if not self.is_vector_env:
    rews = np.array([rews])
self.returns = self.returns * self.gamma * (1 - terminateds) + rews
```
in `step` which accounts for the needed dim in `np.mean(x, axis=0)` which is missing in the new experimental one. Let me verify that, then I'll open another PR including a small test.
