### ISSUE TITLE
[Bug Report] RecordVideo generates black images after the first record

### ISSUE THREAD

**Issue by navigator8972** [Farama-Foundation/Gymnasium#312]
### Describe the bug

Trying to use RecordVideo to log offscreen rendering in RL training loop. The first time recording works but the ones afterwards return zero images. The old mujoco_py seems to work though.

### Code example

```shell
import gymnasium as gym
# import gym

from gymnasium.wrappers.record_video import RecordVideo
# from gym.wrappers.record_video import RecordVideo

def capture_video_on_episode(episdoe_id):
    return True

def collect(env, num=100):
    for _ in range(num):
        env.step(env.action_space.sample())

native_env = gym.make("Humanoid", render_mode="rgb_array")

env = RecordVideo(native_env, "./", capture_video_on_episode)

env.reset()
collect(env, 50)
env.close()

env.reset()
collect(env, 50)
env.close()
```

### System info

* pip install gymnasium
* gymnasium.__version__: '0.27.1'
* Mac OS Ventura
* Python version: 3.9.15

### Additional context

This was initially observed and tracked with https://github.com/thu-ml/tianshou/issues/800. A further test found the issue is reproducible independent of the repo. Commenting out gymnasium to use gym in the above code works as intended.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
@navigator8972 Thanks for the issue. I thought originally there would be an issue due to the first close causing an issue but removing that doesn't seem to remove the issue.
For now, I would follow what @dohmjan and use the experimental version of the wrapper which will replace the wrapper in a couple of months.

@younik Do you know what is going wrong with code above?

**Comment by navigator8972** [comment]
Yes, RecordVideoV0 does not suffer from this issue in my tests. Will close this as solved with workaround. The issue can be similarly reproduced with old openai gym with a little adjustment. See the issue above with tianshou repo.

**Comment by younik** [comment]
The problem is the following line: https://github.com/Farama-Foundation/Gymnasium/blob/76559ed553cffc3e5082227b0a8acea461273e84/gymnasium/wrappers/monitoring/video_recorder.py#L148

That function is called every time a new video should be saved, thus it should not close the environment as well (the naming is a bit confusing)
Glad to hear that everything works with the new version
