### ISSUE TITLE
[Bug Report] Documentation is duplicated on the website

### ISSUE THREAD

**Issue by valentin-cnt** [Farama-Foundation/Gymnasium#320]
### Describe the bug

A lot of the documentation on the website contain duplicated information.

Example:
- https://gymnasium.farama.org/api/wrappers/reward_wrappers/#gymnasium.wrappers.NormalizeReward
- https://gymnasium.farama.org/api/wrappers/observation_wrappers/#gymnasium.wrappers.FlattenObservation
- https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.StepAPICompatibility

This is due because Sphinx collects the docstring for the `class` and the `__init__` which often say the same thing.
One solution could be to move every relevant documentation to the `class` docstring and configure Sphinx not to take the `__init__`. (I'm not familiar with Sphinx but I would guess there's a way)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
This is a good point, for now, as the wrappers will be replaced by the experimental ones I would prefer to update those. 

The question is what information should be stored in the class docstring and the constructor (`__init__`) docstring. The problem is that the first line of the constructor docstring is not obviously different from the class docstring. My ideas are

1. We could modify the `pydocstyle` checker on the constructor docstring specifically on wrappers such that the first line is not necessary. 
2. Agree on a simple and effective first line of the constructor for pydocstyle and the website
3. Modify sphinx to ignore the first line of the constructor of wrappers only.

**Comment by valentin-cnt** [comment]
I agree, I will to look for a way to parse the constructor (`__init__`) docstring to keep only the Args part
