### ISSUE TITLE
[Proposal] Observation Space `dtype` change to `np.float32` for Mujoco environments

### ISSUE THREAD

**Issue by sonelu** [Farama-Foundation/Gymnasium#447]
### Proposal

Change the `dtype` for the observation space to `np.float32` in Mujoco environments, or use a constructor argument to decide which data type to use.

### Motivation

At the moment Mujoco environments are configured with `dtype=np.float64` observation spaces. This has a significant impact on off-policy agents that use replay buffers as is practically doubles the memory requirements for the buffers.

Is there a reason why they have to be like that or can we switch to `np.float32`? Alternatively that could be a parameter in the constructor with the default `np.float64`, allowing the user to switch it if necessary.

### Pitch

Replay buffer is the most resource consuming resource and the current settings unnecessarily require significant memory for it.

### Alternatives

Arguably the environment can be wrapped and the the change can be included there, but having the original environment changed seems cleaner.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by pseudo-rnd-thoughts** [comment]
I suspect the reason is that the Mujoco uses `float64` and the original devs didn't want to change the type for the reasons you list above. 
For backward compatibility, I don't think we will change the `dtype` of the observation however we have added a `DtypeObservation` wrapper that users can use to convert the observation data to a preferred type (`gymnasium.experimental.wrappers.DtypeObservationV0`).

I would be interested in the training as like you say there shouldn't be a difference in the agent performance but RL is weird in its training.

**Comment by pseudo-rnd-thoughts** [comment]
That would be great, thanks for offering to do that

**Comment by ikamensh** [comment]
For reference envpool creator thinks action should be float64 :) 
https://github.com/sail-sg/envpool/issues/260
