### ISSUE TITLE
[Bug Report] Box contains treats float(inf) unexpectedly

### ISSUE THREAD

**Issue by mzat-msft** [Farama-Foundation/Gymnasium#493]
### Describe the bug

When checking if a number is contained in a ``Box`` I get ``True`` but I expect it to be ``False``.

### Code example

```shell
Python 3.10.11 (main, May  4 2023, 15:26:51) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gymnasium.spaces import Box
>>> Box(low=float("inf"), high=float("inf")).contains([-10])
True
>>> Box(low=-float("-inf"), high=float("inf")).contains([-10])
True
```

### System info

>>> gymnasium.__version__
'0.26.3'

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
does this happen only with `inf`>

**Comment by pseudo-rnd-thoughts** [comment]
Ok, this is a really weird bug from the outlook 

In short, `Box` internally changes the `inf` to ` -inf` which is why `contains([-10])` is true.

In particular, the [get_inf](https://github.com/Farama-Foundation/Gymnasium/blob/54a268f3d825781451d88d54d3053a2a63ebec64/gymnasium/spaces/box.py#L284) function ignores the actual value passed just knowing that it was an infinite (ignoring that you passed a positive infinity as the lower bound) and returns a positive or negative infinity depending on if it is for the lower and upper bound.

I agree that this is a hidden behaviour that you don't expected from the outside. 
@mzat-msft Would you be interested in making a PR that raise a warning or error to users that they are doing something silly and should update to `-inf`

**Comment by jjshoots** [comment]
@mzat-msft This is actually a very interesting case.

What are you exactly trying to achieve with using equal sign infinites as bounds for the Box space?
I ask this because this behaviour (in theory) should produce a degenerate space:
- what values belong in the space?
- what should `is_bounded("above")` return on a space of `Box(-inf, -inf)`?

Fixing this issue _is_ possible (though I'm more keen to just make the space throw an error to disallow this behaviour).
If you could let us know what use case this is for, perhaps it would allow us to make more informed decisions when fixing this "bug".

**Comment by mzat-msft** [comment]
There's no use case per se. There was this typo in our code and just thought it would be useful for you to know about it.
I agree that raising a ``ValueError`` is probably this. Would that apply to ``Box(x, x)`` too?

**Comment by pseudo-rnd-thoughts** [comment]
> Would that apply to Box(x, x) too?

I think it would be reasonable to do so but `np.random.uniform(low=x, high=x)` works therefore, I don't think we should disable it
