### ISSUE TITLE
[Proposal] Add conda release

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/Gymnasium#5]
With the ability to make github actions on release, add conda releases to github release workflow

**Comment by kir0ul** [comment]
Why not using the standard [conda-forge](https://conda-forge.org/) channel?
I'm asking this because it seems to me that the existing tooling built around conda-forge is hard to match with any simpler GH Action, which could mean less maintenance in the long run.

**Comment by pseudo-rnd-thoughts** [comment]
Agreed, looking at it more, I think we just need to make a staged recipe for the project with each of the options

**Comment by kir0ul** [comment]
I was looking a bit into it, the first problem I encountered is that pygame is not packaged for Conda (but I guess you knew that already) and from what I could read it looks pretty tricky to package, but I'll try to have a look anyway.

Related issues: https://github.com/pygame/pygame/issues/1953, https://github.com/conda-forge/staged-recipes/pull/19665, https://github.com/pygame/pygame/issues/3320.

**Comment by h-vetinari** [comment]
gym is [already](https://github.com/conda-forge/gym-feedstock/) in conda-forge, including most of the optional outputs (but stuck on 0.21 due to the addition of the extremely trick pygame dependency with 0.22). please help us get things packaged there rather than do your own thing. Though the good news is that https://github.com/conda-forge/staged-recipes/pull/19665 seems to be nearing completion...

**Comment by jjyyxx** [comment]
I apologize for interrupting the thread, but I was curious about the progress of the "Official Conda packaging" mentioned in Roadmap #12. Since February is coming to an end, I was wondering if there are any updates you could share with us regarding the status of this feature. Thank you for your time and efforts!

**Comment by pseudo-rnd-thoughts** [comment]
@h-vetinari has been doing an amazing job on conda, and there already exists a conda install for gymnasium. 
https://github.com/conda-forge/gymnasium-feedstock

**Comment by h-vetinari** [comment]
We don't have 0.27 yet as there'll be some new dependencies that'll take some work. Join the discussion in https://github.com/conda-forge/gymnasium-feedstock/issues/1 if you want, and any help is always welcome (I can try to help out, but probably won't be able to lead this effort; the gym->gymnasium transition already took a bunch of time I didn't really have planned for this 🙃).

**Comment by pseudo-rnd-thoughts** [comment]
Gymnasium on conda has been updated to the latest version, thank you to @h-vetinari  and @ChristofKaufmann for all of their hardwork
https://github.com/conda-forge/gymnasium-feedstock

**Comment by h-vetinari** [comment]
Happy to hear it!

Now that we've caught up in terms of versions, it's would probably be worth mentioning under the installation instructions? We also support windows. :)

```
conda install -c conda-forge gymnasium  # or "gymnasium-all" for all supported optional extensions
```

**Comment by pseudo-rnd-thoughts** [comment]
yes, good point, @h-vetinari could you make a pr for this?

**Comment by h-vetinari** [comment]
> yes, good point, @h-vetinari could you make a pr for this?

This seems to have fallen through the cracks, sorry - anyone else up for it?

**Comment by pseudo-rnd-thoughts** [comment]
Is this just a documentation update? Sorry, I have forgotten what we wanted to do
