### ISSUE TITLE
[Proposal] Numeric is in a Box Space

### ISSUE THREAD

**Issue by rusu24edward** [Farama-Foundation/Gymnasium#574]
### Proposal

I think it makes sense that a single numerical value could be in a box space. For example, suppose I have space
``` python
space = Box(0, 4, (1,))
a = space.sample()[0] # This will give me a single numerical value
a in space # This will be false
```
A single number is not in a Box space. This fails because np.asarray(SOME_NUMBER) produces a 0-dimensional array.

### Motivation

I write simulations that rely on Box observation spaces of one dimension. It's natural for me that those simulations just output a single numerical value for observation instead of an array or list of that value.

### Pitch

Change the `contains` function in `Box` to allow for single numbers when the Box space has shape `(1,)`.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by RedTachyon** [comment]
I think similar proposals bounced around the issues and potentially the discord, but I don't think this is a good thing to do. The idea of a box is that a specific element of that space is an array. While there is an obvious correspondence between numbers and arrays of size `[1]`, they are not the same objects, and the only reason why they can sometimes be treated similarly is python's insanity.

The good news is that a `Box(0, 4, ())` might be what you're looking for, since zero-dim arrays have more of a claim to being the same thing as numbers.

**Comment by rusu24edward** [comment]
> the only reason why they can sometimes be treated similarly is python's insanity.

For the record, I don't think this is insanity. It's not precise, but I'm okay with that because I like python for its flexibility over its precision. If this is an idea that has bounced around a bit, then I think that many people may feel the same way. What do we gain by distinguishing between `[1]` and `1` in `Box(0, 4, (1,))`? Precision for precision's sake? Then everything fits perfectly in the little list of rules that we have for this object? So what? I think `[1]` and `1` are functionally the same in this case, so unless there are important use cases that require this distinction, then I believe functionality and flexibility should win over precision and neatness.
