### ISSUE TITLE
[Bug Report] Tricky behaviour with gymnasium.spaces.Dict

### ISSUE THREAD

**Issue by alex404** [Farama-Foundation/Gymnasium#579]
### Describe the bug

The `keys` method of `gymnasium.spaces.Dict` returns a `KeysView` object, which causes statements of the form `ky in d.keys()` to return `False`, even if the `ky` is in the dictionary `d`.

I'm not sure what the exact purpose of `KeysView` is, so maybe this behaviour makes sense, but I spent a long time trying to figure this out for myself, and perhaps it at least warrants clarification somewhere. Converting the `KeysView` object to a list resolves the issue.

### Code example

```shell
import gymnasium

bx = gymnasium.spaces.Box(0,1)
d = gymnasium.spaces.Dict({ 'a' : bx, 'b' : bx })

# Prints False twice
kys = d.keys()
for ky in kys:
    print(ky in kys)

# Prints True twice
lkys = list(kys)
for ky in lkys:
    print(ky in lkys)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by RedTachyon** [comment]
I can try to look at it later, but it seems to be caused by having `Dict` implement the `Mapping` type, I think this might be messed due to `Space` overwriting the `__contains__` method, thanks for reporting!

**Comment by pseudo-rnd-thoughts** [comment]
I remember a similar in Gym about the keys function returns the wrong data type, like @RedTachyon the issue I believe is with overriding `Mapping`.

**Comment by pseudo-rnd-thoughts** [comment]
This is a much more complex bug than I originally thought
In short, the `spaces.Dict` inherits from `typing.Mapping` which contains its own implementation of `keys`
This function, `keys`, will return a `KeyView(self)`. 
Now, when we do `"a" in space.keys()` then it will run `"a" in self` (where self is the original dict), the problem is that `Space` overrides the `__contains__` function (i.e., the function run when `in` is used)

Therefore, the solution is the we do need to overwrite the `keys` function ourselves, to return `KeysView(self.spaces)` which will use the actual dict in the check and not have the issue. 

Apologies if the explanation above doesn't make sense, there are 4/5 interweaving problems

I will make a PR that address the issue and adds a test to prevent it being an issue in the future

**Comment by alex404** [comment]
Cool! Thanks.
