### ISSUE TITLE
[Question] Deprecation warning for wrapper space attributes?

### ISSUE THREAD

**Issue by vmoens** [Farama-Foundation/Gymnasium#725]
### Question

The latest gymnasium version warns that wrappers reward spec won't be accessible in the same way in v1.0
I'm not sure how to interpret this:
```
rl/lib/python3.9/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.reward_space to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.reward_space` for environment variables or `env.get_wrapper_attr('reward_space')` that will search the reminding wrappers.
```

My questions are:
1. Why this deprecation? I saw somewhere that vectorized envs will now be a separated class. I seems from here that wrapped env will distanciate themselves from regular envs. Why are all these classes which were interchangeable become more different? If anything one would expect them to become closer to each other with time.
2. Specifically for reward spaces: what does this mean in practice? In torchrl, we have a series of wrappers for gymnasium envs, what do we have to do to anticipate these changes?
3. Is there a way big "customers" of gymnasium would be asked for feedback before deciding these bc-breaking changes in the future? Is there a list of people we can subscribe to that would make us aware of these changes before they are enacted?

Thanks

**Comment by pseudo-rnd-thoughts** [comment]
Hey, thanks for the questions, I'm separating out the top question from 1.

0. In short, Gym / Gymnasium has a "hack" that override the `Wrapper.__getattr__` function. This function is called anytime python fails to find a variable in a class. This was important as most of the time users are interacting with the top level wrapper but may want to interact with the base environment or other wrappers. Therefore, the `Wrapper.__getattr__` was used recursively down the environment stack to get variable not in the top wrapper. The problem is that this causes issues with setting attributes as the sister function, `__setattribute__` was never implemented. Also, a more minor problem in our opinion is that users don't realise this is happening or what class they are interacting with. 
In summary, despite accessing `gravity`, the user can't modify it likewise.  
```python
env = gym.make("CartPole-v1")
print(env)
# <TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v1>>>>>
env.reset()
print(env.gravity)
# 9.8
env.gravity = 1
print(env.gravity, env.env.gravity, env.unwrapped.gravity)
# 1 9.8 9.8
```
See https://github.com/Farama-Foundation/Gymnasium/issues/357 for the full issue

The large problem with this is in async and sync vector environment where you can't modify the base environment's variables which is why we realised this bug in the hack existed. Finally, a rare but weird error exists if you try to access a variable that doesn't exist in a wrapper before `super().__init__(env)` is called as `env` doesn't exist so `__getattr__` will be called infinitely. We have found this a particularly large problem in [shimmy](https://github.com/farama-Foundation/shimmy) for deepmind projects.  

Therefore, we decided rather than implement `__setattribute__` it would be simpler and easier for users to understand what is happening through implementing `get_wrapper_attr` and `set_wrapper_attr` functions to recursively get or set variables otherwise the user will only interact with the object that they are actually interacting with.

1. Part of the discussion is given in https://github.com/Farama-Foundation/Gymnasium/issues/32, in short, while `Env` and `VectorEnv`, we believe that there are subtle but important changes, particularly with `step` and for wrappers. Our aim was to simplify the difference between `Env` and `VectorEnv` such that users can easily swap between the two. Importantly, this should allow users to clearly differentiate between the vector and non-vector code along with promoting vector-only projects that while previously would work with Gymnasium, we believe could be incorrectly used due to several details
2. Following the answer to question 0, if you are accessing a variable that you know if not in the top level object, then you need to change to `env.unwrapped.variable_name` for accessing for a variable in the base environment, otherwise, `env.get_wrapper_attr(variable_name)`
3. A lot of the time, we use issues to discuss variables but we also have an internal team of developers who develop and work on problems. @jkterry1 Do you have any thoughts on this?
