### ISSUE TITLE
[Bug Report] gymnasium.error.NamespaceNotFound: Namespace gym_examples not found.

### ISSUE THREAD

**Issue by NghiaPhamttk27** [Farama-Foundation/Gymnasium#742]
### Describe the bug

I've followed https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/#creating-a-package.
I have successfully registered the environment, but when I try to use that environment, I receive the error mentioned in the title. I have seen a similar issue here (https://github.com/Farama-Foundation/Gymnasium/issues/400), but all of my code is using Gymnasium (you can see it on my GitHub). Did I do something wrong? If so, please help me.

My github code: https://github.com/NghiaPhamttk27/GridWorld/tree/main

![Screenshot 2023-10-16 224234](https://github.com/Farama-Foundation/Gymnasium/assets/145578401/a6b7396b-23de-4721-8438-a479f9582c88)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by lucasbasquerotto** [comment]
@NghiaPhamttk27 You closed this issue, is that because you solved the problem? I'm facing the same issue.

I followed the tutorial https://gymnasium.farama.org/tutorials/gymnasium_basics/environment_creation/ and installed the environment with `pip install -e gym-examples` from outside the directory (I also installed with `pip install -e .` in the directory to see if it works).

The installation is done successfully, but when I try to use it like:

```
import gymnasium
env = gymnasium.make('gym_examples/GridWorld-v0')
```

it gives the error:

```
gymnasium.error.NamespaceNotFound: Namespace gym_examples not found. Have you installed the proper package for gym_examples?
```

I tried to call import `gym_examples` to see if it does any difference, but the error persists.

There's an issue about this at https://github.com/Farama-Foundation/gym-examples/issues/16, but it says that gym is not supported anymore and to use this repository (the funny thing is that the gymnasium tutorial uses the gym package, perhaps because it wasn't updated yet).

Anyway, I changed imports from gym to gymnasium, and gym to gymnasium in setup.py to see if it solves, the issue, but to no avail.
