### ISSUE TITLE
[Question] Why not define the terminate function for some goal tasks like reacher-v4?

### ISSUE THREAD

**Issue by zichunxx** [Farama-Foundation/Gymnasium#776]
### Question

Hi!

After reading some [documents](https://farama.org/Gymnasium-Terminated-Truncated-Step-API) about truncation and termination, I think the terminate function is used to end the episode in some typical goal-related tasks, e.g., reacher-v4. But the terminate function seems not to be defined explicitly in the reacher-v4 env. Why? 

Thanks in advance.

**Comment by Kallinteris-Andreas** [comment]
The `reacher-v5` environment does not terminate when the goal is reached because, that is how it was first implemented in `reacher-v0` and this is how we have been carrying it forward.

I assume (though I have not tested it) that if it did terminate upon reaching the goal, then the trained policy would result in reaching the goal with high velocity, and therefore leaving the goal immediately after reaching it.

Thought could also have been an oversight from the original developers of `reacher-v0`.

I have not been able to find the original development documents for the reacher environment, so I am not sure about the design goals.


In either case the environment has such low complexity that it practically does not affect its solvability with training algorithms, for more complex manipulation problems you can check the `gymansium-robotics` repo.

**Comment by Kallinteris-Andreas** [comment]
> main reason for the missing terminate function is to maintain the target state after the goal has been reached

That is definitely one of the consequences of not having a terminate functions (though it may not be the most efficient way to achieve such a result)
