### ISSUE TITLE
[Question] How to cite?

### ISSUE THREAD

**Issue by juhannc** [Farama-Foundation/Gymnasium#82]
### Question

How should Gymnasium be cited?
Can you provide a bibtex entry for Gymnasium?

**Comment by pseudo-rnd-thoughts** [comment]
We are planning on publishing an academic paper for Gymnasium in a similar way to PettingZoo has an academic paper however this is a long way off, probably when 1.0 is finished. 
Therefore, in the meantime time could you just link to our github.

**Comment by kir0ul** [comment]
Just throwing this here in case that's helpful, you may want to consider the [Journal of Open Source Software](https://joss.theoj.org/) for where to publish the academic paper.

**Comment by kir0ul** [comment]
Another thing I was thinking is, in the meantime there isn't a paper yet, we could still add a `CITATION.cff` file (see https://citation-file-format.github.io/), so that at least people know how to cite this work and can easily get a BibTeX string. Then once there is a paper we can just modify the `CITATION.cff` file to add a `journal`, `doi`, etc. fields, like explained in [About CITATION files docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files).

**Comment by pseudo-rnd-thoughts** [comment]
The problem is more related to the number of authors. Jordan would like to get confirmation and the correct details for the core developers (including old contributors). Just the time required, this is not a priority currently

**Comment by Kallinteris-Andreas** [comment]
has been added to the description @pseudo-rnd-thoughts  close
