### ISSUE TITLE
[Question] Why was `FuncEnv.state_info()` renamed to `FuncEnv.initial_info()`?

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/Gymnasium#855]
### Question

In https://github.com/Farama-Foundation/Gymnasium/pull/818/ `state_info` was renamed to `initial_info` with no explanation, what was the reason?

I suggest that this change be reversed, as you have state info in each step for some environments.

@RedTachyon 
Thanks

**Comment by RedTachyon** [comment]
It was renamed at some point in the past due to a misunderstanding about this function's intention,  it should definitely be `state_info`. To make things more fun, the current code has a messed up transform with `self.state_info = func(self.initial_info)` due to this. 

So this needs to be fixed, changing it consistently to `state_info`. If you or someone else can do it, that'd be great, otherwise I'll do it at some point soon-ish
